version: '3.8'

services:
  freeradius:
    image: "2stacks/freeradius"
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      #- "./configs/radius/users:/etc/raddb/users" #disabled for mysql db of users instead
      - "./configs/radius/clients.conf:/etc/raddb/clients.conf"
      - "./configs/radius/mods-available/eap:/etc/raddb/mods-available/eap"
      - "./configs/radius/proxy.conf:/etc/raddb/proxy.conf"
      - "./configs/radius/certs/ca.der:/etc/raddb/certs/ca.der"
      - "./configs/radius/certs/ca.key:/etc/raddb/certs/ca.key"
      - "./configs/radius/certs/ca.pem:/etc/raddb/certs/ca.pem"
      - "./configs/radius/certs/server.crt:/etc/raddb/certs/server.crt"
      - "./configs/radius/certs/server.csr:/etc/raddb/certs/server.csr"
      - "./configs/radius/certs/server.key:/etc/raddb/certs/server.key"
      - "./configs/radius/certs/server.pem:/etc/raddb/certs/server.pem"
      - "./configs/radius/certs/server.p12:/etc/raddb/certs/server.p12"
      - "./configs/radius/certs/client.crt:/etc/raddb/certs/client.crt"
      - "./configs/radius/certs/client.csr:/etc/raddb/certs/client.csr"
      - "./configs/radius/certs/client.key:/etc/raddb/certs/client.key"
      - "./configs/radius/certs/client.pem:/etc/raddb/certs/client.pem"
      - "./configs/radius/certs/client.p12:/etc/raddb/certs/client.p12"

      #- freeradius-configs:/etc/raddb/
    environment:
      #- DB_NAME=radius
      - DB_HOST=mysql
      #- DB_USER=radius
      #- DB_PASS=radpass
      #- DB_PORT=3307
      - RADIUS_KEY=testing123
      #- RAD_CLIENTS=10.0.0.0/24
      - RAD_DEBUG=yes
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    networks:
      - backend

  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - "./configs/mysql/master/data:/var/lib/mysql"
      #- "./configs/mysql/master/conf.d:/etc/mysql/conf.d"
      - "./configs/mysql/radius.sql:/docker-entrypoint-initdb.d/radius.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radpass
      - MYSQL_DATABASE=radius
    restart: always
    networks:
      - backend

networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.0.0/24